window.TOLData = {
  CONDITIONS: [
    {
      value: 'cystitis',
      domain: 'infection',
      subtype: 'urinary',
      en: 'Uncomplicated cystitis',
      fr: 'Cystite non compliquee',
      summary: {
        en: 'Repeat adult urinary prescribing with renal thresholds, allergy checks, and fast copy output.',
        fr: 'Prescription urinaire repetee avec seuils renaux, allergies et sortie de copie rapide.',
      },
    },
    {
      value: 'cellulitis',
      domain: 'infection',
      subtype: 'skin',
      en: 'Cellulitis',
      fr: 'Cellulite',
      summary: {
        en: 'A skin-infection review that compares first-line oral options and allergy alternatives.',
        fr: 'Une revue d infection cutanee qui compare premieres lignes et alternatives.',
      },
    },
    {
      value: 'ringworm',
      domain: 'infection',
      subtype: 'skin',
      en: 'Ringworm / tinea corporis',
      fr: 'Teigne corporelle / tinea corporis',
      summary: {
        en: 'A common topical-first pathway with an oral escalation branch for more extensive disease.',
        fr: 'Un parcours souvent topique avec escalade orale si atteinte plus etendue.',
      },
    },
    {
      value: 'otitis-media',
      domain: 'infection',
      subtype: 'ear',
      en: 'Acute otitis media',
      fr: 'Otite moyenne aigue',
      summary: {
        en: 'An ear-infection branch that keeps first-line and allergy alternatives visible.',
        fr: 'Une branche d infection de l oreille avec premiere ligne et alternatives visibles.',
      },
    },
    {
      value: 'chlamydia',
      domain: 'sti',
      subtype: 'common-sti',
      en: 'Chlamydia review',
      fr: 'Revue chlamydia',
      summary: {
        en: 'A simple STI review that contrasts first-line adult therapy with fallback single-dose formatting.',
        fr: 'Une revue IST simple qui oppose therapie adulte premiere ligne et option dose unique.',
      },
    },
    {
      value: 'pharyngitis',
      domain: 'infection',
      subtype: 'throat',
      en: 'Strep pharyngitis',
      summary: {
        en: 'Group A strep throat review with first-line penicillin pathway and allergy alternatives.',
      },
    },
    {
      value: 'sinusitis',
      domain: 'infection',
      subtype: 'respiratory',
      en: 'Acute bacterial sinusitis',
      summary: {
        en: 'Sinus infection that has persisted beyond viral window, warranting antibiotic consideration.',
      },
    },
    {
      value: 'bronchitis-bacterial',
      domain: 'infection',
      subtype: 'respiratory',
      en: 'Acute bacterial bronchitis',
      summary: {
        en: 'Lower respiratory bacterial review for cases beyond simple viral cough.',
      },
    },
    {
      value: 'impetigo',
      domain: 'infection',
      subtype: 'skin',
      en: 'Impetigo',
      summary: {
        en: 'Superficial skin infection review with topical-first and oral escalation pathways.',
      },
    },
    {
      value: 'uti-male',
      domain: 'infection',
      subtype: 'urinary',
      en: 'UTI in males',
      summary: {
        en: 'Complicated urinary pathway requiring longer course and broader coverage consideration.',
      },
    },
    {
      value: 'conjunctivitis',
      domain: 'infection',
      subtype: 'eye',
      en: 'Bacterial conjunctivitis',
      summary: {
        en: 'Eye infection review with topical antibiotic options and red-flag screening.',
      },
    },
    {
      value: 'gonorrhea',
      domain: 'sti',
      subtype: 'common-sti',
      en: 'Gonorrhea review',
      summary: {
        en: 'Dual therapy review with IM ceftriaxone plus oral coverage for uncomplicated gonorrhea.',
      },
    },
    {
      value: 'trichomoniasis',
      domain: 'sti',
      subtype: 'common-sti',
      en: 'Trichomoniasis review',
      summary: {
        en: 'Metronidazole-based review for confirmed or presumptive trichomonal infection.',
      },
    },
    {
      value: 'bv',
      domain: 'sti',
      subtype: 'vaginal',
      en: 'Bacterial vaginosis',
      summary: {
        en: 'First-line metronidazole pathway with oral and vaginal options.',
      },
    },
    {
      value: 'vulvovaginal-candidiasis',
      domain: 'sti',
      subtype: 'vaginal',
      en: 'Vulvovaginal candidiasis',
      summary: {
        en: 'Antifungal review with OTC topical and prescription oral fluconazole options.',
      },
    },
    /* ─── New infection conditions ─── */
    {
      value: 'shingles',
      domain: 'infection',
      subtype: 'skin',
      en: 'Herpes zoster (shingles)',
      summary: { en: 'Antiviral review for acute shingles within the 72-hour treatment window.' },
    },
    {
      value: 'dental-abscess',
      domain: 'infection',
      subtype: 'dental',
      en: 'Dental abscess',
      summary: { en: 'Antibiotic bridging for periapical or periodontal abscess pending dental follow-up.' },
    },
    {
      value: 'pyelonephritis',
      domain: 'infection',
      subtype: 'urinary',
      en: 'Acute pyelonephritis (outpatient)',
      summary: { en: 'Upper urinary tract infection requiring broader-spectrum outpatient oral therapy.' },
    },
    {
      value: 'otitis-externa',
      domain: 'infection',
      subtype: 'ear',
      en: 'Otitis externa',
      summary: { en: 'Outer ear infection review with topical antibiotic/steroid drops.' },
    },
    {
      value: 'cap',
      domain: 'infection',
      subtype: 'respiratory',
      en: 'Community-acquired pneumonia (mild)',
      summary: { en: 'Outpatient oral antibiotic review for mild community-acquired pneumonia.' },
    },
    {
      value: 'lyme-disease',
      domain: 'infection',
      subtype: 'systemic',
      en: 'Early Lyme disease',
      summary: { en: 'Doxycycline-first review for erythema migrans or confirmed early Lyme.' },
    },
    /* ─── New STI condition ─── */
    {
      value: 'herpes-simplex',
      domain: 'sti',
      subtype: 'common-sti',
      en: 'Herpes simplex (genital)',
      summary: { en: 'Antiviral review for initial or recurrent genital HSV episodes.' },
    },
    /* ─── Mental health ─── */
    {
      value: 'depression',
      domain: 'mental-health',
      subtype: 'mood',
      en: 'Major depressive disorder',
      summary: { en: 'First-line SSRI review for new or recurrent depression in primary care.' },
    },
    {
      value: 'gad',
      domain: 'mental-health',
      subtype: 'anxiety-disorder',
      en: 'Generalized anxiety disorder',
      summary: { en: 'SSRI/SNRI-based review for GAD with non-benzodiazepine alternatives.' },
    },
    {
      value: 'insomnia',
      domain: 'mental-health',
      subtype: 'sleep',
      en: 'Insomnia (short-term)',
      summary: { en: 'Short-term pharmacotherapy review after sleep hygiene measures are insufficient.' },
    },
    /* ─── Cardiovascular ─── */
    {
      value: 'hypertension',
      domain: 'cardiovascular',
      subtype: 'bp',
      en: 'Essential hypertension',
      summary: { en: 'First-line antihypertensive review per Canadian guidelines (Hypertension Canada).' },
    },
    {
      value: 'hyperlipidemia',
      domain: 'cardiovascular',
      subtype: 'lipid',
      en: 'Hyperlipidemia',
      summary: { en: 'Statin-first review for primary or secondary cardiovascular risk reduction.' },
    },
    /* ─── Endocrine ─── */
    {
      value: 'type2-diabetes',
      domain: 'endocrine',
      subtype: 'diabetes',
      en: 'Type 2 diabetes (initial)',
      summary: { en: 'Metformin-first review for newly diagnosed or uncontrolled type 2 diabetes.' },
    },
    {
      value: 'hypothyroidism',
      domain: 'endocrine',
      subtype: 'thyroid',
      en: 'Hypothyroidism',
      summary: { en: 'Levothyroxine initiation and titration review for primary hypothyroidism.' },
    },
    {
      value: 'vitamin-d-deficiency',
      domain: 'endocrine',
      subtype: 'nutritional',
      en: 'Vitamin D deficiency',
      summary: { en: 'Supplementation review for confirmed low 25-OH vitamin D.' },
    },
    {
      value: 'iron-deficiency',
      domain: 'endocrine',
      subtype: 'nutritional',
      en: 'Iron deficiency anemia',
      summary: { en: 'Oral iron replacement review for confirmed iron deficiency with or without anemia.' },
    },
    /* ─── GI ─── */
    {
      value: 'gerd',
      domain: 'gi',
      subtype: 'acid-reflux',
      en: 'GERD / acid reflux',
      summary: { en: 'Step-up PPI review for gastroesophageal reflux not controlled by lifestyle measures.' },
    },
    {
      value: 'h-pylori',
      domain: 'gi',
      subtype: 'peptic',
      en: 'H. pylori eradication',
      summary: { en: 'Triple or quadruple therapy review for confirmed Helicobacter pylori infection.' },
    },
    /* ─── MSK / pain ─── */
    {
      value: 'low-back-pain',
      domain: 'msk',
      subtype: 'back-pain',
      en: 'Acute low back pain',
      summary: { en: 'NSAID-first review for non-specific mechanical low back pain without red flags.' },
    },
    {
      value: 'osteoarthritis',
      domain: 'msk',
      subtype: 'joint',
      en: 'Osteoarthritis',
      summary: { en: 'Stepped analgesic review for symptomatic OA of knee, hip, or hand.' },
    },
    {
      value: 'gout-flare',
      domain: 'msk',
      subtype: 'crystal',
      en: 'Acute gout flare',
      summary: { en: 'Acute anti-inflammatory review for confirmed or clinically suspected gout flare.' },
    },
    {
      value: 'migraine',
      domain: 'msk',
      subtype: 'headache',
      en: 'Migraine (acute)',
      summary: { en: 'Acute migraine treatment review with NSAID and triptan options.' },
    },
    /* ─── Dermatology ─── */
    {
      value: 'acne-vulgaris',
      domain: 'dermatology',
      subtype: 'acne-derm',
      en: 'Acne vulgaris',
      summary: { en: 'Topical-first acne review with oral escalation for moderate-severe disease.' },
    },
    {
      value: 'atopic-dermatitis',
      domain: 'dermatology',
      subtype: 'eczema-derm',
      en: 'Atopic dermatitis / eczema',
      summary: { en: 'Topical steroid and emollient review for mild-to-moderate atopic dermatitis.' },
    },
    /* ─── Women's health ─── */
    {
      value: 'ocp-combined',
      domain: 'womens-health',
      subtype: 'contraception',
      en: 'Combined oral contraceptive',
      summary: { en: 'Combined OCP selection review with VTE risk screening.' },
    },
    {
      value: 'menopause-hrt',
      domain: 'womens-health',
      subtype: 'perimenopause',
      en: 'Menopause HRT',
      summary: { en: 'Hormone replacement therapy review for vasomotor and urogenital symptoms.' },
    },
    /* ─── ENT / allergy ─── */
    {
      value: 'allergic-rhinitis',
      domain: 'ent',
      subtype: 'nasal',
      en: 'Allergic rhinitis',
      summary: { en: 'Intranasal steroid and antihistamine review for seasonal or perennial allergic rhinitis.' },
    },
    /* ─── Chronic respiratory ─── */
    {
      value: 'copd-exacerbation',
      domain: 'resp-chronic',
      subtype: 'obstructive',
      en: 'COPD acute exacerbation',
      summary: { en: 'Short-course steroid and antibiotic review for acute COPD exacerbation managed outpatient.' },
    },
    /* ─── Auto-generated from formulary (102 conditions) ─── */
    {
    value: 'anaphylaxis',
    domain: 'allergy',
    subtype: 'allergy-immunology',
    en: 'Anaphylaxis',
    summary: { en: 'Adrenergic agonist-based review for anaphylaxis in primary care.' },
  },
  {
    value: 'angioedema',
    domain: 'allergy',
    subtype: 'allergy-immunology',
    en: 'Angioedema',
    summary: { en: 'Antihistamine-based review for angioedema in primary care.' },
  },
  {
    value: 'food-allergy',
    domain: 'allergy',
    subtype: 'allergy-immunology',
    en: 'Food Allergy',
    summary: { en: 'Anaphylaxis prevention-based review for food allergy in primary care.' },
  },
  {
    value: 'atrial-fibrillation-flutter',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Atrial Fibrillation/Flutter',
    summary: { en: 'Rate control – beta blocker-based review for atrial fibrillation/flutter in primary care.' },
  },
  {
    value: 'chest-pain-initial',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Chest Pain (initial)',
    summary: { en: 'Organic nitrate-based review for chest pain (initial) in primary care.' },
  },
  {
    value: 'edema',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Edema',
    summary: { en: 'Loop diuretic-based review for edema in primary care.' },
  },
  {
    value: 'heart-failure',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Heart Failure',
    summary: { en: 'ACE inhibitor-based review for heart failure in primary care.' },
  },
  {
    value: 'hypertension-combination-therapy',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Hypertension – Combination Therapy',
    summary: { en: 'ACE inhibitor + CCB-based review for hypertension – combination therapy in primary care.' },
  },
  {
    value: 'hypertensive-emergency-urgency',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Hypertensive Emergency/Urgency',
    summary: { en: 'Central alpha agonist-based review for hypertensive emergency/urgency in primary care.' },
  },
  {
    value: 'peripheral-arterial-disease',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Peripheral Arterial Disease',
    summary: { en: 'Antiplatelet-based review for peripheral arterial disease in primary care.' },
  },
  {
    value: 'stable-angina-cad',
    domain: 'cardiovascular',
    subtype: 'cardiac-general',
    en: 'Stable Angina/CAD',
    summary: { en: 'Beta blocker-based review for stable angina/cad in primary care.' },
  },
  {
    value: 'cutaneous-warts-verruca',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Cutaneous Warts (verruca)',
    summary: { en: 'Keratolytic-based review for cutaneous warts (verruca) in primary care.' },
  },
  {
    value: 'fungal-infections-candida',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Fungal Infections – Candida',
    summary: { en: 'Azole antifungal-based review for fungal infections – candida in primary care.' },
  },
  {
    value: 'fungal-infections-tinea',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Fungal Infections – Tinea',
    summary: { en: 'Topical allylamine-based review for fungal infections – tinea in primary care.' },
  },
  {
    value: 'pityriasis-versicolor',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Pityriasis Versicolor',
    summary: { en: 'Topical antifungal-based review for pityriasis versicolor in primary care.' },
  },
  {
    value: 'psoriasis',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Psoriasis',
    summary: { en: 'Topical corticosteroid-based review for psoriasis in primary care.' },
  },
  {
    value: 'scalp-psoriasis',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Scalp Psoriasis',
    summary: { en: 'Keratolytic/vitamin D analogue-based review for scalp psoriasis in primary care.' },
  },
  {
    value: 'tinea-corporis-pedis-cruris-ringworm-athlete-s-foot',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Tinea Corporis/Pedis/Cruris (Ringworm/Athlete’s foot)',
    summary: { en: 'Topical imidazole-based review for tinea corporis/pedis/cruris (ringworm/athlete’s foot) in primary care.' },
  },
  {
    value: 'urticaria',
    domain: 'dermatology',
    subtype: 'derm-general',
    en: 'Urticaria',
    summary: { en: 'Non-sedating antihistamine-based review for urticaria in primary care.' },
  },
  {
    value: 'epistaxis',
    domain: 'ent',
    subtype: 'ent-general',
    en: 'Epistaxis',
    summary: { en: 'Local pressure-based review for epistaxis in primary care.' },
  },
  {
    value: 'vertigo-bppv',
    domain: 'ent',
    subtype: 'ent-general',
    en: 'Vertigo/BPPV',
    summary: { en: 'Nonpharmacologic-based review for vertigo/bppv in primary care.' },
  },
  {
    value: 'b12-folate-deficiency',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'B12/Folate Deficiency',
    summary: { en: 'Cobalamin-based review for b12/folate deficiency in primary care.' },
  },
  {
    value: 'hypercalcemia',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Hypercalcemia',
    summary: { en: 'Hydration and diuresis-based review for hypercalcemia in primary care.' },
  },
  {
    value: 'hyperthyroidism',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Hyperthyroidism',
    summary: { en: 'Beta blocker-based review for hyperthyroidism in primary care.' },
  },
  {
    value: 'hypocalcemia',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Hypocalcemia',
    summary: { en: 'Calcium supplement-based review for hypocalcemia in primary care.' },
  },
  {
    value: 'obesity',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Obesity',
    summary: { en: 'Lifestyle modification-based review for obesity in primary care.' },
  },
  {
    value: 'osteoporosis',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Osteoporosis',
    summary: { en: 'Vitamin D and calcium-based review for osteoporosis in primary care.' },
  },
  {
    value: 'pcos',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'PCOS',
    summary: { en: 'Combined oral contraceptive-based review for pcos in primary care.' },
  },
  {
    value: 'prediabetes',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Prediabetes',
    summary: { en: 'Lifestyle modification-based review for prediabetes in primary care.' },
  },
  {
    value: 'type-1-diabetes',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Type 1 Diabetes',
    summary: { en: 'Basal-bolus insulin therapy-based review for type 1 diabetes in primary care.' },
  },
  {
    value: 'type-2-diabetes-combination-therapy',
    domain: 'endocrine',
    subtype: 'endo-general',
    en: 'Type 2 Diabetes – Combination Therapy',
    summary: { en: 'Biguanide + DPP‑4 inhibitor-based review for type 2 diabetes – combination therapy in primary care.' },
  },
  {
    value: 'anal-fissure',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Anal Fissure',
    summary: { en: 'Conservative measures-based review for anal fissure in primary care.' },
  },
  {
    value: 'constipation',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Constipation',
    summary: { en: 'Bulk-forming agent-based review for constipation in primary care.' },
  },
  {
    value: 'diarrhea',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Diarrhea',
    summary: { en: 'Oral rehydration solution-based review for diarrhea in primary care.' },
  },
  {
    value: 'fatty-liver-hepatitis',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Fatty Liver/Hepatitis',
    summary: { en: 'Lifestyle intervention-based review for fatty liver/hepatitis in primary care.' },
  },
  {
    value: 'gallstones',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Gallstones',
    summary: { en: 'Analgesic-based review for gallstones in primary care.' },
  },
  {
    value: 'hemorrhoids-piles',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Hemorrhoids (Piles)',
    summary: { en: 'Conservative measures-based review for hemorrhoids (piles) in primary care.' },
  },
  {
    value: 'hemorrhoids-fissures',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'Hemorrhoids/Fissures',
    summary: { en: 'Nonpharmacologic-based review for hemorrhoids/fissures in primary care.' },
  },
  {
    value: 'ibs',
    domain: 'gi',
    subtype: 'gi-general',
    en: 'IBS',
    summary: { en: 'Lifestyle modification-based review for ibs in primary care.' },
  },
  {
    value: 'anogenital-warts',
    domain: 'sti',
    subtype: 'gu-sti',
    en: 'Anogenital Warts',
    summary: { en: 'Topical immune response modifier-based review for anogenital warts in primary care.' },
  },
  {
    value: 'dementia',
    domain: 'geriatrics',
    subtype: 'geriatric-general',
    en: 'Dementia',
    summary: { en: 'Cholinesterase inhibitor-based review for dementia in primary care.' },
  },
  {
    value: 'end-of-life-care',
    domain: 'geriatrics',
    subtype: 'geriatric-general',
    en: 'End-of-Life Care',
    summary: { en: 'Opioid analgesic-based review for end-of-life care in primary care.' },
  },
  {
    value: 'falls-prevention',
    domain: 'geriatrics',
    subtype: 'geriatric-general',
    en: 'Falls Prevention',
    summary: { en: 'Vitamin D and calcium-based review for falls prevention in primary care.' },
  },
  {
    value: 'frailty',
    domain: 'geriatrics',
    subtype: 'geriatric-general',
    en: 'Frailty',
    summary: { en: 'Nonpharmacologic-based review for frailty in primary care.' },
  },
  {
    value: 'abnormal-uterine-bleeding',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'Abnormal Uterine Bleeding',
    summary: { en: 'NSAID-based review for abnormal uterine bleeding in primary care.' },
  },
  {
    value: 'dysmenorrhea',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'Dysmenorrhea',
    summary: { en: 'NSAID-based review for dysmenorrhea in primary care.' },
  },
  {
    value: 'emergency-contraception',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'Emergency Contraception',
    summary: { en: 'Progestin emergency pill-based review for emergency contraception in primary care.' },
  },
  {
    value: 'pelvic-inflammatory-disease',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'Pelvic Inflammatory Disease',
    summary: { en: 'Cephalosporin-based review for pelvic inflammatory disease in primary care.' },
  },
  {
    value: 'sti-chlamydia',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'STI – Chlamydia',
    summary: { en: 'Tetracycline-based review for sti – chlamydia in primary care.' },
  },
  {
    value: 'sti-gonorrhea',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'STI – Gonorrhea',
    summary: { en: 'Cephalosporin-based review for sti – gonorrhea in primary care.' },
  },
  {
    value: 'vaginitis-trichomoniasis',
    domain: 'womens-health',
    subtype: 'gynecology',
    en: 'Vaginitis (Trichomoniasis)',
    summary: { en: 'Nitroimidazole-based review for vaginitis (trichomoniasis) in primary care.' },
  },
  {
    value: 'b12-deficiency',
    domain: 'hematology',
    subtype: 'hematology-general',
    en: 'B12 Deficiency',
    summary: { en: 'Vitamin B12-based review for b12 deficiency in primary care.' },
  },
  {
    value: 'folate-deficiency',
    domain: 'hematology',
    subtype: 'hematology-general',
    en: 'Folate Deficiency',
    summary: { en: 'Folic acid-based review for folate deficiency in primary care.' },
  },
  {
    value: 'iron-deficiency-anemia',
    domain: 'hematology',
    subtype: 'hematology-general',
    en: 'Iron Deficiency Anemia',
    summary: { en: 'Oral iron-based review for iron deficiency anemia in primary care.' },
  },
  {
    value: 'leukopenia-neutropenia',
    domain: 'hematology',
    subtype: 'hematology-general',
    en: 'Leukopenia (Neutropenia)',
    summary: { en: 'Colony-stimulating factor-based review for leukopenia (neutropenia) in primary care.' },
  },
  {
    value: 'polycythemia-vera',
    domain: 'hematology',
    subtype: 'hematology-general',
    en: 'Polycythemia Vera',
    summary: { en: 'Phlebotomy-based review for polycythemia vera in primary care.' },
  },
  {
    value: 'thrombocytopenia-itp',
    domain: 'hematology',
    subtype: 'hematology-general',
    en: 'Thrombocytopenia (ITP)',
    summary: { en: 'Corticosteroid-based review for thrombocytopenia (itp) in primary care.' },
  },
  {
    value: 'latent-tuberculosis',
    domain: 'infection',
    subtype: 'infectious-general',
    en: 'Latent Tuberculosis',
    summary: { en: 'Antimycobacterial-based review for latent tuberculosis in primary care.' },
  },
  {
    value: 'meningitis-triage',
    domain: 'infection',
    subtype: 'infectious-general',
    en: 'Meningitis Triage',
    summary: { en: 'Third-generation cephalosporin-based review for meningitis triage in primary care.' },
  },
  {
    value: 'mononucleosis-ebv',
    domain: 'infection',
    subtype: 'infectious-general',
    en: 'Mononucleosis (EBV)',
    summary: { en: 'Supportive care-based review for mononucleosis (ebv) in primary care.' },
  },
  {
    value: 'pyrexia-of-unknown-origin',
    domain: 'infection',
    subtype: 'infectious-general',
    en: 'Pyrexia of Unknown Origin',
    summary: { en: 'Diagnostic evaluation-based review for pyrexia of unknown origin in primary care.' },
  },
  {
    value: 'viral-syndrome',
    domain: 'infection',
    subtype: 'infectious-general',
    en: 'Viral Syndrome',
    summary: { en: 'Analgesic/antipyretic-based review for viral syndrome in primary care.' },
  },
  {
    value: 'gout-chronic',
    domain: 'msk',
    subtype: 'msk-general',
    en: 'Gout (Chronic)',
    summary: { en: 'Xanthine oxidase inhibitor-based review for gout (chronic) in primary care.' },
  },
  {
    value: 'sprains-strains',
    domain: 'msk',
    subtype: 'msk-general',
    en: 'Sprains/Strains',
    summary: { en: 'Nonpharmacologic-based review for sprains/strains in primary care.' },
  },
  {
    value: 'tendinitis-bursitis',
    domain: 'msk',
    subtype: 'msk-general',
    en: 'Tendinitis/Bursitis',
    summary: { en: 'NSAID-based review for tendinitis/bursitis in primary care.' },
  },
  {
    value: 'benign-paroxysmal-positional-vertigo-bppv',
    domain: 'neurology',
    subtype: 'neuro-general',
    en: 'Benign Paroxysmal Positional Vertigo (BPPV)',
    summary: { en: 'Maneuver – Epley (Canalith repositioning)-based review for benign paroxysmal positional vertigo (bppv) in primary care.' },
  },
  {
    value: 'cognitive-decline-dementia',
    domain: 'neurology',
    subtype: 'neuro-general',
    en: 'Cognitive Decline/Dementia',
    summary: { en: 'Cholinesterase inhibitor-based review for cognitive decline/dementia in primary care.' },
  },
  {
    value: 'neuropathy-peripheral',
    domain: 'neurology',
    subtype: 'neuro-general',
    en: 'Neuropathy (Peripheral)',
    summary: { en: 'Anticonvulsant-based review for neuropathy (peripheral) in primary care.' },
  },
  {
    value: 'parkinsonism',
    domain: 'neurology',
    subtype: 'neuro-general',
    en: 'Parkinsonism',
    summary: { en: 'Dopamine precursor-based review for parkinsonism in primary care.' },
  },
  {
    value: 'stroke-tia-secondary-prevention',
    domain: 'neurology',
    subtype: 'neuro-general',
    en: 'Stroke/TIA Secondary Prevention',
    summary: { en: 'Antiplatelet-based review for stroke/tia secondary prevention in primary care.' },
  },
  {
    value: 'hypertensive-disorders-of-pregnancy',
    domain: 'obstetrics',
    subtype: 'obstetric-general',
    en: 'Hypertensive Disorders of Pregnancy',
    summary: { en: 'Antiplatelet-based review for hypertensive disorders of pregnancy in primary care.' },
  },
  {
    value: 'nausea-vomiting-in-pregnancy',
    domain: 'obstetrics',
    subtype: 'obstetric-general',
    en: 'Nausea/Vomiting in Pregnancy',
    summary: { en: 'Vitamin B6 & antihistamine-based review for nausea/vomiting in pregnancy in primary care.' },
  },
  {
    value: 'postpartum-care',
    domain: 'obstetrics',
    subtype: 'obstetric-general',
    en: 'Postpartum Care',
    summary: { en: 'NSAID-based review for postpartum care in primary care.' },
  },
  {
    value: 'adhd',
    domain: 'pediatrics',
    subtype: 'peds-general',
    en: 'ADHD',
    summary: { en: 'Stimulant-based review for adhd in primary care.' },
  },
  {
    value: 'peds-acne',
    domain: 'pediatrics',
    subtype: 'peds-general',
    en: 'Acne',
    summary: { en: 'Topical antimicrobial-based review for acne in primary care.' },
  },
  {
    value: 'asthma-wheeze',
    domain: 'pediatrics',
    subtype: 'peds-general',
    en: 'Asthma/Wheeze',
    summary: { en: 'SABA-based review for asthma/wheeze in primary care.' },
  },
  {
    value: 'bronchiolitis',
    domain: 'pediatrics',
    subtype: 'peds-general',
    en: 'Bronchiolitis',
    summary: { en: 'Supportive care-based review for bronchiolitis in primary care.' },
  },
  {
    value: 'enuresis',
    domain: 'pediatrics',
    subtype: 'peds-general',
    en: 'Enuresis',
    summary: { en: 'Behavioural modification-based review for enuresis in primary care.' },
  },
  {
    value: 'fever',
    domain: 'pediatrics',
    subtype: 'peds-general',
    en: 'Fever',
    summary: { en: 'Analgesic/antipyretic-based review for fever in primary care.' },
  },
  {
    value: 'bipolar-disorder-suspected',
    domain: 'mental-health',
    subtype: 'psych-general',
    en: 'Bipolar Disorder (suspected)',
    summary: { en: 'Mood stabilizer-based review for bipolar disorder (suspected) in primary care.' },
  },
  {
    value: 'ptsd',
    domain: 'mental-health',
    subtype: 'psych-general',
    en: 'PTSD',
    summary: { en: 'SSRI-based review for ptsd in primary care.' },
  },
  {
    value: 'panic-disorder',
    domain: 'mental-health',
    subtype: 'psych-general',
    en: 'Panic Disorder',
    summary: { en: 'SSRI-based review for panic disorder in primary care.' },
  },
  {
    value: 'substance-use-disorder-alcohol',
    domain: 'mental-health',
    subtype: 'psych-general',
    en: 'Substance Use Disorder – Alcohol',
    summary: { en: 'Opioid antagonist-based review for substance use disorder – alcohol in primary care.' },
  },
  {
    value: 'substance-use-disorder-opioids',
    domain: 'mental-health',
    subtype: 'psych-general',
    en: 'Substance Use Disorder – Opioids',
    summary: { en: 'Partial opioid agonist-based review for substance use disorder – opioids in primary care.' },
  },
  {
    value: 'suicidality',
    domain: 'mental-health',
    subtype: 'psych-general',
    en: 'Suicidality',
    summary: { en: 'Crisis intervention-based review for suicidality in primary care.' },
  },
  {
    value: 'chronic-kidney-disease',
    domain: 'renal',
    subtype: 'renal-general',
    en: 'Chronic Kidney Disease',
    summary: { en: 'ACE inhibitor-based review for chronic kidney disease in primary care.' },
  },
  {
    value: 'hyperkalemia',
    domain: 'renal',
    subtype: 'renal-general',
    en: 'Hyperkalemia',
    summary: { en: 'Potassium binder-based review for hyperkalemia in primary care.' },
  },
  {
    value: 'hypokalemia',
    domain: 'renal',
    subtype: 'renal-general',
    en: 'Hypokalemia',
    summary: { en: 'Oral potassium-based review for hypokalemia in primary care.' },
  },
  {
    value: 'hyponatremia',
    domain: 'renal',
    subtype: 'renal-general',
    en: 'Hyponatremia',
    summary: { en: 'Free water restriction-based review for hyponatremia in primary care.' },
  },
  {
    value: 'nephrolithiasis',
    domain: 'renal',
    subtype: 'renal-general',
    en: 'Nephrolithiasis',
    summary: { en: 'Analgesic-based review for nephrolithiasis in primary care.' },
  },
  {
    value: 'asthma',
    domain: 'resp-chronic',
    subtype: 'resp-general',
    en: 'Asthma',
    summary: { en: 'SABA-based review for asthma in primary care.' },
  },
  {
    value: 'croup-pediatrics',
    domain: 'resp-chronic',
    subtype: 'resp-general',
    en: 'Croup (Pediatrics)',
    summary: { en: 'Systemic corticosteroid-based review for croup (pediatrics) in primary care.' },
  },
  {
    value: 'obstructive-sleep-apnea',
    domain: 'resp-chronic',
    subtype: 'resp-general',
    en: 'Obstructive Sleep Apnea',
    summary: { en: 'Device – CPAP-based review for obstructive sleep apnea in primary care.' },
  },
  {
    value: 'urti-influenza-like',
    domain: 'resp-chronic',
    subtype: 'resp-general',
    en: 'URTI/Influenza-like',
    summary: { en: 'Analgesic/antipyretic-based review for urti/influenza-like in primary care.' },
  },
  {
    value: 'fibromyalgia',
    domain: 'rheumatology',
    subtype: 'rheum-general',
    en: 'Fibromyalgia',
    summary: { en: 'Tricyclic antidepressant-based review for fibromyalgia in primary care.' },
  },
  {
    value: 'polymyalgia-rheumatica-gca',
    domain: 'rheumatology',
    subtype: 'rheum-general',
    en: 'Polymyalgia Rheumatica/GCA',
    summary: { en: 'Corticosteroid-based review for polymyalgia rheumatica/gca in primary care.' },
  },
  {
    value: 'raynaud-phenomenon',
    domain: 'rheumatology',
    subtype: 'rheum-general',
    en: 'Raynaud Phenomenon',
    summary: { en: 'CCB-based review for raynaud phenomenon in primary care.' },
  },
  {
    value: 'rheumatoid-arthritis-suspected',
    domain: 'rheumatology',
    subtype: 'rheum-general',
    en: 'Rheumatoid Arthritis (suspected)',
    summary: { en: 'NSAID-based review for rheumatoid arthritis (suspected) in primary care.' },
  },
  {
    value: 'erectile-dysfunction',
    domain: 'urology',
    subtype: 'urology-general',
    en: 'Erectile Dysfunction',
    summary: { en: 'PDE5 inhibitor-based review for erectile dysfunction in primary care.' },
  },
  {
    value: 'luts-bph',
    domain: 'urology',
    subtype: 'urology-general',
    en: 'LUTS/BPH',
    summary: { en: 'Alpha-1 blocker-based review for luts/bph in primary care.' },
  },
  {
    value: 'prostatitis-acute-bacterial',
    domain: 'urology',
    subtype: 'urology-general',
    en: 'Prostatitis (acute bacterial)',
    summary: { en: 'Fluoroquinolone-based review for prostatitis (acute bacterial) in primary care.' },
  },
  {
    value: 'testicular-pain-epididymitis',
    domain: 'urology',
    subtype: 'urology-general',
    en: 'Testicular Pain (Epididymitis)',
    summary: { en: 'Cephalosporin-based review for testicular pain (epididymitis) in primary care.' },
  },,
  ],
  CONDITION_SYMPTOMS: {
    cystitis: [
      { value: 'dysuria', en: 'Dysuria', fr: 'Dysurie' },
      { value: 'frequency', en: 'Urinary frequency', fr: 'Frequence urinaire' },
      { value: 'urgency', en: 'Urgency', fr: 'Urgence' },
      { value: 'flankPain', en: 'Flank pain', fr: 'Douleur au flanc' },
      { value: 'fever', en: 'Fever', fr: 'Fievre' },
    ],
    cellulitis: [
      { value: 'redness', en: 'Spreading redness', fr: 'Rougeur qui s etend' },
      { value: 'warmth', en: 'Warmth', fr: 'Chaleur' },
      { value: 'swelling', en: 'Swelling', fr: 'Enflure' },
      { value: 'purulence', en: 'Purulent area', fr: 'Zone purulente' },
      { value: 'fever', en: 'Fever', fr: 'Fievre' },
    ],
    ringworm: [
      { value: 'itch', en: 'Itch', fr: 'Demangeaison' },
      { value: 'annularRash', en: 'Annular rash', fr: 'Plaque annulaire' },
      { value: 'scaling', en: 'Scaling', fr: 'Squames' },
      { value: 'scalpScale', en: 'Scalp involvement', fr: 'Atteinte du cuir chevelu' },
      { value: 'extensiveRash', en: 'Extensive / multiple lesions', fr: 'Atteinte etendue / multiple' },
    ],
    'otitis-media': [
      { value: 'earPain', en: 'Ear pain', fr: 'Douleur a l oreille' },
      { value: 'fever', en: 'Fever', fr: 'Fievre' },
      { value: 'discharge', en: 'Drainage / discharge', fr: 'Ecoulement' },
      { value: 'recurrentHistory', en: 'Recurrent episodes', fr: 'Episodes recurrents' },
    ],
    chlamydia: [
      { value: 'dysuria', en: 'Dysuria', fr: 'Dysurie' },
      { value: 'discharge', en: 'Discharge', fr: 'Ecoulement' },
      { value: 'partnerPositive', en: 'Partner positive', fr: 'Partenaire positif' },
      { value: 'pelvicPain', en: 'Pelvic pain', fr: 'Douleur pelvienne' },
      { value: 'testPending', en: 'Test pending / presumptive treatment', fr: 'Test en attente / traitement presumptif' },
    ],
    pharyngitis: [
      { value: 'soreThroat', en: 'Sore throat' },
      { value: 'fever', en: 'Fever' },
      { value: 'tonsilExudate', en: 'Tonsillar exudate' },
      { value: 'lymphadenopathy', en: 'Cervical lymphadenopathy' },
      { value: 'rapidStrepPos', en: 'Rapid strep positive' },
    ],
    sinusitis: [
      { value: 'facialPain', en: 'Facial pain/pressure' },
      { value: 'nasalDischarge', en: 'Purulent nasal discharge' },
      { value: 'fever', en: 'Fever' },
      { value: 'prolongedSymptoms', en: 'Symptoms >10 days' },
      { value: 'doubleWorsening', en: 'Double worsening pattern' },
    ],
    'bronchitis-bacterial': [
      { value: 'productiveCough', en: 'Productive cough' },
      { value: 'fever', en: 'Fever' },
      { value: 'prolongedCough', en: 'Cough >10 days' },
      { value: 'dyspnea', en: 'Dyspnea' },
      { value: 'crackleLungSounds', en: 'Crackles on auscultation' },
    ],
    impetigo: [
      { value: 'honeyCrust', en: 'Honey-colored crusting' },
      { value: 'bullae', en: 'Bullae present' },
      { value: 'spreading', en: 'Spreading lesions' },
      { value: 'perioral', en: 'Perioral location' },
    ],
    'uti-male': [
      { value: 'dysuria', en: 'Dysuria' },
      { value: 'frequency', en: 'Urinary frequency' },
      { value: 'fever', en: 'Fever' },
      { value: 'flankPain', en: 'Flank pain' },
      { value: 'prostateSymptoms', en: 'Prostate symptoms' },
    ],
    conjunctivitis: [
      { value: 'purulentDischarge', en: 'Purulent discharge' },
      { value: 'eyeRedness', en: 'Conjunctival injection' },
      { value: 'crusting', en: 'Morning crusting' },
      { value: 'contactLens', en: 'Contact lens wearer' },
    ],
    gonorrhea: [
      { value: 'discharge', en: 'Urethral/vaginal discharge' },
      { value: 'dysuria', en: 'Dysuria' },
      { value: 'partnerPositive', en: 'Partner positive' },
      { value: 'pharyngealExposure', en: 'Pharyngeal exposure' },
    ],
    trichomoniasis: [
      { value: 'vaginalDischarge', en: 'Frothy vaginal discharge' },
      { value: 'odor', en: 'Malodorous discharge' },
      { value: 'dysuria', en: 'Dysuria' },
      { value: 'partnerPositive', en: 'Partner positive' },
    ],
    bv: [
      { value: 'vaginalDischarge', en: 'Thin gray discharge' },
      { value: 'fishy', en: 'Fishy odor' },
      { value: 'cluePositive', en: 'Clue cells on wet mount' },
      { value: 'recurrent', en: 'Recurrent episodes' },
    ],
    'vulvovaginal-candidiasis': [
      { value: 'itching', en: 'Vulvar itching' },
      { value: 'thickDischarge', en: 'Thick white discharge' },
      { value: 'erythema', en: 'Vulvar erythema' },
      { value: 'recurrent', en: 'Recurrent (4+/year)' },
    ],
    shingles: [
      { value: 'vesicularRash', en: 'Vesicular rash in dermatome' },
      { value: 'pain', en: 'Burning / neuropathic pain' },
      { value: 'within72h', en: 'Within 72 hours of onset' },
      { value: 'ophthalmic', en: 'Ophthalmic branch (V1)' },
      { value: 'immunocompromised', en: 'Immunocompromised patient' },
    ],
    'dental-abscess': [
      { value: 'toothPain', en: 'Severe tooth pain' },
      { value: 'swelling', en: 'Facial swelling' },
      { value: 'fever', en: 'Fever' },
      { value: 'trismus', en: 'Trismus / limited opening' },
      { value: 'draining', en: 'Draining sinus tract' },
    ],
    pyelonephritis: [
      { value: 'flankPain', en: 'Flank pain' },
      { value: 'fever', en: 'Fever / chills' },
      { value: 'nausea', en: 'Nausea / vomiting' },
      { value: 'dysuria', en: 'Dysuria' },
      { value: 'cvaTenderness', en: 'CVA tenderness' },
    ],
    'otitis-externa': [
      { value: 'earPain', en: 'Ear pain / tragal tenderness' },
      { value: 'itching', en: 'Ear canal itching' },
      { value: 'discharge', en: 'Otorrhea' },
      { value: 'canalEdema', en: 'Canal edema / narrowing' },
      { value: 'diabetic', en: 'Diabetic / immunocompromised' },
    ],
    cap: [
      { value: 'cough', en: 'Productive cough' },
      { value: 'fever', en: 'Fever' },
      { value: 'dyspnea', en: 'Dyspnea' },
      { value: 'chestPain', en: 'Pleuritic chest pain' },
      { value: 'consolidation', en: 'Consolidation on exam / X-ray' },
    ],
    'lyme-disease': [
      { value: 'erythemaMigrans', en: 'Erythema migrans rash' },
      { value: 'tickBite', en: 'Known tick bite' },
      { value: 'arthralgia', en: 'Arthralgias / myalgias' },
      { value: 'fever', en: 'Fever / fatigue' },
      { value: 'endemic', en: 'Endemic area exposure' },
    ],
    'herpes-simplex': [
      { value: 'vesicles', en: 'Genital vesicles / ulcers' },
      { value: 'pain', en: 'Pain / burning' },
      { value: 'firstEpisode', en: 'First episode' },
      { value: 'recurrent', en: 'Recurrent episode' },
      { value: 'prodrome', en: 'Prodromal tingling' },
    ],
    depression: [
      { value: 'lowMood', en: 'Persistent low mood' },
      { value: 'anhedonia', en: 'Loss of interest / anhedonia' },
      { value: 'sleepChange', en: 'Sleep disturbance' },
      { value: 'fatigue', en: 'Fatigue / low energy' },
      { value: 'concentration', en: 'Poor concentration' },
      { value: 'appetiteChange', en: 'Appetite / weight change' },
    ],
    gad: [
      { value: 'excessiveWorry', en: 'Excessive worry (>6 months)' },
      { value: 'restlessness', en: 'Restlessness' },
      { value: 'muscleTension', en: 'Muscle tension' },
      { value: 'sleepDifficulty', en: 'Difficulty sleeping' },
      { value: 'irritability', en: 'Irritability' },
      { value: 'panicFeatures', en: 'Panic-like features' },
    ],
    insomnia: [
      { value: 'sleepOnset', en: 'Difficulty falling asleep' },
      { value: 'sleepMaintenance', en: 'Frequent awakenings' },
      { value: 'earlyWaking', en: 'Early morning awakening' },
      { value: 'daytimeImpairment', en: 'Daytime impairment' },
      { value: 'chronicDuration', en: 'Duration > 3 months' },
    ],
    hypertension: [
      { value: 'stageOne', en: 'Stage 1 (140-159 / 90-99)' },
      { value: 'stageTwo', en: 'Stage 2 (160+ / 100+)' },
      { value: 'diabetes', en: 'Comorbid diabetes' },
      { value: 'ckd', en: 'Chronic kidney disease' },
      { value: 'africanDescent', en: 'African descent' },
      { value: 'heartFailure', en: 'Heart failure history' },
    ],
    hyperlipidemia: [
      { value: 'highLdl', en: 'LDL > 5.0 mmol/L' },
      { value: 'moderateRisk', en: 'FRS 10-19% (moderate)' },
      { value: 'highRisk', en: 'FRS ≥ 20% or equivalent' },
      { value: 'diabetes', en: 'Comorbid diabetes' },
      { value: 'familyHx', en: 'Family history of early CVD' },
      { value: 'statinIntolerance', en: 'Prior statin intolerance' },
    ],
    'type2-diabetes': [
      { value: 'a1cMild', en: 'A1C 6.5-7.9%' },
      { value: 'a1cModerate', en: 'A1C 8.0-9.4%' },
      { value: 'a1cSevere', en: 'A1C ≥ 9.5%' },
      { value: 'obesity', en: 'BMI ≥ 30' },
      { value: 'cvdRisk', en: 'Established CVD or high risk' },
      { value: 'ckd', en: 'eGFR < 60 / CKD' },
    ],
    hypothyroidism: [
      { value: 'fatigue', en: 'Fatigue' },
      { value: 'coldIntolerance', en: 'Cold intolerance' },
      { value: 'weightGain', en: 'Weight gain' },
      { value: 'constipation', en: 'Constipation' },
      { value: 'elevatedTSH', en: 'TSH elevated (confirmed)' },
    ],
    'vitamin-d-deficiency': [
      { value: 'lowLevel', en: '25-OH D < 50 nmol/L' },
      { value: 'veryLow', en: '25-OH D < 25 nmol/L' },
      { value: 'boneHealth', en: 'Osteoporosis / fracture risk' },
      { value: 'malabsorption', en: 'Malabsorption concern' },
    ],
    'iron-deficiency': [
      { value: 'lowFerritin', en: 'Ferritin < 30' },
      { value: 'anemia', en: 'Hemoglobin below normal' },
      { value: 'fatigue', en: 'Fatigue / dyspnea' },
      { value: 'menstrualLoss', en: 'Heavy menstrual bleeding' },
      { value: 'giLoss', en: 'Suspected GI blood loss' },
    ],
    gerd: [
      { value: 'heartburn', en: 'Heartburn / pyrosis' },
      { value: 'regurgitation', en: 'Regurgitation' },
      { value: 'dysphagia', en: 'Dysphagia' },
      { value: 'chronicCough', en: 'Chronic cough / throat clearing' },
      { value: 'alarmFeatures', en: 'Alarm features (weight loss, anemia)' },
    ],
    'h-pylori': [
      { value: 'dyspepsia', en: 'Dyspepsia / epigastric pain' },
      { value: 'confirmedTest', en: 'Positive H. pylori test' },
      { value: 'pepticUlcer', en: 'Known peptic ulcer' },
      { value: 'priorFailure', en: 'Prior eradication failure' },
    ],
    'low-back-pain': [
      { value: 'acuteOnset', en: 'Acute onset (< 6 weeks)' },
      { value: 'muscleTension', en: 'Paraspinal muscle spasm' },
      { value: 'limitedRom', en: 'Limited range of motion' },
      { value: 'radiculopathy', en: 'Radicular symptoms' },
      { value: 'noRedFlags', en: 'No red flags confirmed' },
    ],
    osteoarthritis: [
      { value: 'kneeOa', en: 'Knee involvement' },
      { value: 'hipOa', en: 'Hip involvement' },
      { value: 'handOa', en: 'Hand involvement' },
      { value: 'morningStiffness', en: 'Morning stiffness < 30 min' },
      { value: 'crepitus', en: 'Crepitus on exam' },
      { value: 'giRisk', en: 'GI risk factors (age, hx)' },
    ],
    'gout-flare': [
      { value: 'mtpJoint', en: 'First MTP joint involved' },
      { value: 'acuteSwelling', en: 'Acute monoarticular swelling' },
      { value: 'priorGout', en: 'Prior gout diagnosis' },
      { value: 'elevatedUrate', en: 'Elevated serum urate' },
      { value: 'ckd', en: 'CKD / renal concern' },
    ],
    migraine: [
      { value: 'unilateral', en: 'Unilateral headache' },
      { value: 'pulsating', en: 'Pulsating quality' },
      { value: 'nausea', en: 'Nausea / vomiting' },
      { value: 'photophobia', en: 'Photophobia / phonophobia' },
      { value: 'aura', en: 'Aura present' },
      { value: 'frequent', en: 'Frequent attacks (>4/month)' },
    ],
    'acne-vulgaris': [
      { value: 'comedonal', en: 'Comedonal (blackheads / whiteheads)' },
      { value: 'inflammatory', en: 'Inflammatory papules / pustules' },
      { value: 'nodulocystic', en: 'Nodular / cystic lesions' },
      { value: 'facial', en: 'Facial involvement' },
      { value: 'scarring', en: 'Scarring present' },
    ],
    'atopic-dermatitis': [
      { value: 'pruritus', en: 'Pruritus / itching' },
      { value: 'flexuralRash', en: 'Flexural distribution' },
      { value: 'chronicRelapsing', en: 'Chronic relapsing course' },
      { value: 'mildDisease', en: 'Mild (limited area)' },
      { value: 'moderateDisease', en: 'Moderate (widespread)' },
    ],
    'ocp-combined': [
      { value: 'regularCycles', en: 'Regular cycle desired' },
      { value: 'dysmenorrhea', en: 'Dysmenorrhea' },
      { value: 'acneBenefit', en: 'Acne treatment benefit desired' },
      { value: 'noVteRisk', en: 'No VTE risk factors' },
      { value: 'smokerOver35', en: 'Smoker age > 35' },
    ],
    'menopause-hrt': [
      { value: 'hotFlashes', en: 'Hot flashes / night sweats' },
      { value: 'vaginalDryness', en: 'Vaginal dryness' },
      { value: 'sleepDisruption', en: 'Sleep disruption' },
      { value: 'recentMenopause', en: 'Within 10 years of menopause' },
      { value: 'uterusIntact', en: 'Uterus intact (needs progesterone)' },
    ],
    'allergic-rhinitis': [
      { value: 'sneezing', en: 'Sneezing' },
      { value: 'nasalCongestion', en: 'Nasal congestion' },
      { value: 'rhinorrhea', en: 'Clear rhinorrhea' },
      { value: 'eyeSymptoms', en: 'Itchy / watery eyes' },
      { value: 'seasonal', en: 'Seasonal pattern' },
      { value: 'perennial', en: 'Perennial / year-round' },
    ],
    'copd-exacerbation': [
      { value: 'increasedDyspnea', en: 'Increased dyspnea' },
      { value: 'increasedSputum', en: 'Increased sputum volume' },
      { value: 'purulentSputum', en: 'Purulent sputum' },
      { value: 'anthonisen2of3', en: 'Anthonisen 2 of 3 criteria' },
      { value: 'priorExacerbation', en: 'History of frequent exacerbations' },
    ],
  },
  DEFAULT_TEMPLATES: [
    {
      id: 'tpl-cystitis-adult-ca',
      name: 'Adult uncomplicated cystitis quick pack',
      condition: 'cystitis',
      defaultMedication: 'nitrofurantoin',
      ageMin: 18,
      ageMax: 70,
      weightMin: 45,
      weightMax: 120,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes:
        'Use when the doctor is already comfortable this is uncomplicated lower urinary symptoms. Re-check red flags before fast apply.',
    },
    {
      id: 'tpl-ringworm-topical',
      name: 'Localized ringworm topical starter',
      condition: 'ringworm',
      defaultMedication: 'clotrimazole-topical',
      ageMin: 12,
      ageMax: 80,
      weightMin: 25,
      weightMax: 180,
      emrType: 'oscar',
      region: 'CA',
      policyModel: 'local',
      notes:
        'Use for body ringworm that still looks localized. Escalate if scalp or extensive involvement is present.',
    },
    {
      id: 'tpl-cellulitis-oral-us',
      name: 'Adult cellulitis oral review',
      condition: 'cellulitis',
      defaultMedication: 'cephalexin',
      ageMin: 18,
      ageMax: 90,
      weightMin: 45,
      weightMax: 180,
      emrType: 'epic',
      region: 'US',
      policyModel: 'national',
      notes:
        'Use for routine outpatient cellulitis review. Keep allergy and purulence checks visible before fast apply.',
    },
    {
      id: 'tpl-chlamydia-quick-us',
      name: 'Adult chlamydia quick template',
      condition: 'chlamydia',
      defaultMedication: 'doxycycline-sti',
      ageMin: 18,
      ageMax: 70,
      weightMin: 40,
      weightMax: 160,
      emrType: 'athena',
      region: 'US',
      policyModel: 'national',
      notes:
        'Built for repeat outpatient adult STI workflows. Do not skip pregnancy, allergy, or broader pelvic-pain review.',
    },
    {
      id: 'tpl-pharyngitis-ca',
      name: 'Strep throat quick pack',
      condition: 'pharyngitis',
      defaultMedication: 'penicillin-v',
      ageMin: 5,
      ageMax: 65,
      weightMin: 15,
      weightMax: 120,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'Standard penicillin-first strep throat template. Check for penicillin allergy before fast apply.',
    },
    {
      id: 'tpl-sinusitis-us',
      name: 'Acute sinusitis oral review',
      condition: 'sinusitis',
      defaultMedication: 'amoxicillin-sinus',
      ageMin: 18,
      ageMax: 80,
      weightMin: 45,
      weightMax: 150,
      emrType: 'epic',
      region: 'US',
      policyModel: 'national',
      notes: 'Amoxicillin first-line for bacterial sinusitis. Ensure symptoms >10 days or double worsening.',
    },
    {
      id: 'tpl-uti-male-ca',
      name: 'Male UTI extended course',
      condition: 'uti-male',
      defaultMedication: 'tmp-smx-male',
      ageMin: 18,
      ageMax: 85,
      weightMin: 50,
      weightMax: 150,
      emrType: 'oscar',
      region: 'CA',
      policyModel: 'local',
      notes: 'Longer course for male UTI. Consider prostate involvement. Check sulfa allergy.',
    },
    {
      id: 'tpl-bv-quick',
      name: 'BV metronidazole quick',
      condition: 'bv',
      defaultMedication: 'metronidazole-oral',
      ageMin: 16,
      ageMax: 55,
      weightMin: 40,
      weightMax: 130,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'Standard oral metronidazole for BV. Warn about alcohol interaction.',
    },
    {
      id: 'tpl-depression-sertraline-ca',
      name: 'Depression sertraline starter',
      condition: 'depression',
      defaultMedication: 'sertraline',
      ageMin: 18,
      ageMax: 75,
      weightMin: 40,
      weightMax: 150,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'First-line SSRI for new depression. Start low, titrate in 2-4 weeks. Screen for bipolar before initiating.',
    },
    {
      id: 'tpl-hypertension-ramipril-ca',
      name: 'Hypertension ramipril starter',
      condition: 'hypertension',
      defaultMedication: 'ramipril',
      ageMin: 18,
      ageMax: 85,
      weightMin: 45,
      weightMax: 160,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'First-line ACE inhibitor per Hypertension Canada. Check K+ and creatinine at 2 weeks.',
    },
    {
      id: 'tpl-diabetes-metformin-ca',
      name: 'T2DM metformin initiation',
      condition: 'type2-diabetes',
      defaultMedication: 'metformin',
      ageMin: 18,
      ageMax: 80,
      weightMin: 50,
      weightMax: 180,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'Metformin first-line per Diabetes Canada. Start 500 mg daily, titrate over 4 weeks.',
    },
    {
      id: 'tpl-gerd-ppi-ca',
      name: 'GERD PPI 4-week trial',
      condition: 'gerd',
      defaultMedication: 'omeprazole',
      ageMin: 18,
      ageMax: 85,
      weightMin: 40,
      weightMax: 160,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'Standard 4-week PPI trial. Step down to PRN or H2RA if symptoms resolve.',
    },
    {
      id: 'tpl-oa-naproxen-ca',
      name: 'OA naproxen short course',
      condition: 'osteoarthritis',
      defaultMedication: 'naproxen-oa',
      ageMin: 40,
      ageMax: 80,
      weightMin: 50,
      weightMax: 150,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'Oral NSAID for OA flare. Use lowest effective dose, shortest duration. Add PPI if GI risk.',
    },
    {
      id: 'tpl-allergic-rhinitis-ca',
      name: 'Allergic rhinitis nasal steroid',
      condition: 'allergic-rhinitis',
      defaultMedication: 'fluticasone-nasal',
      ageMin: 12,
      ageMax: 80,
      weightMin: 30,
      weightMax: 150,
      emrType: 'pssuite',
      region: 'CA',
      policyModel: 'local',
      notes: 'Intranasal corticosteroid first-line for moderate-severe allergic rhinitis.',
    },
  ],
  SCENARIOS: [
    {
      id: 'guided-ringworm',
      title: { en: 'Guided ringworm review', fr: 'Revue guidee teigne' },
      copy: {
        en: 'Starts broad, narrows to skin infection, then adds optional rash clues.',
        fr: 'Commence large, se precise vers infection cutanee, puis ajoute indices.',
      },
      state: {
        workflowMode: 'guided',
        region: 'CA',
        emrType: 'pssuite',
        language: 'en',
        policyModel: 'local',
        age: 28,
        weight: 74,
        sex: 'male',
        egfr: 95,
        hepaticRisk: 'normal',
        pregnancy: 'no',
        domain: 'infection',
        subtype: 'skin',
        condition: 'ringworm',
        symptoms: ['itch', 'annularRash', 'scaling'],
        allergies: [],
        currentMeds: [],
        templateId: 'tpl-ringworm-topical',
      },
    },
    {
      id: 'template-cystitis',
      title: { en: 'Saved template cystitis', fr: 'Modele enregistre cystite' },
      copy: {
        en: 'Shows the fast-apply path with a clinician-owned urinary template and PS Suite copy.',
        fr: 'Montre le mode rapide avec modele urinaire et copie PS Suite.',
      },
      state: {
        workflowMode: 'template',
        region: 'CA',
        emrType: 'pssuite',
        language: 'en',
        policyModel: 'local',
        age: 33,
        weight: 68,
        sex: 'female',
        egfr: 82,
        hepaticRisk: 'normal',
        pregnancy: 'no',
        domain: 'infection',
        subtype: 'urinary',
        condition: 'cystitis',
        symptoms: ['dysuria', 'frequency'],
        allergies: [],
        currentMeds: [],
        templateId: 'tpl-cystitis-adult-ca',
      },
    },
    {
      id: 'guided-cellulitis-allergy',
      title: { en: 'Guided cellulitis with allergy', fr: 'Cellulite guidee avec allergie' },
      copy: {
        en: 'Shows allergy and medication burden changing what stays comfortable.',
        fr: 'Montre comment allergie et charge medicamenteuse changent les options.',
      },
      state: {
        workflowMode: 'guided',
        region: 'US',
        emrType: 'epic',
        language: 'en',
        policyModel: 'national',
        age: 71,
        weight: 79,
        sex: 'male',
        egfr: 58,
        hepaticRisk: 'mild',
        pregnancy: 'na',
        domain: 'infection',
        subtype: 'skin',
        condition: 'cellulitis',
        symptoms: ['redness', 'warmth', 'swelling', 'fever'],
        allergies: ['penicillin'],
        currentMeds: ['warfarin', 'statin'],
        templateId: 'tpl-cellulitis-oral-us',
      },
    },
    {
      id: 'template-sti',
      title: { en: 'Saved STI template', fr: 'Modele IST enregistre' },
      copy: {
        en: 'Shows a fast-apply STI template with U.S.-style copy output and patient-fit checks.',
        fr: 'Montre un modele IST rapide avec sortie copie style US et controles patient.',
      },
      state: {
        workflowMode: 'template',
        region: 'US',
        emrType: 'athena',
        language: 'en',
        policyModel: 'national',
        age: 26,
        weight: 62,
        sex: 'male',
        egfr: 90,
        hepaticRisk: 'normal',
        pregnancy: 'no',
        domain: 'sti',
        subtype: 'common-sti',
        condition: 'chlamydia',
        symptoms: ['partnerPositive', 'discharge'],
        allergies: [],
        currentMeds: [],
        templateId: 'tpl-chlamydia-quick-us',
      },
    },
    {
      id: 'guided-pharyngitis',
      title: { en: 'Guided strep throat' },
      copy: {
        en: 'Common pediatric/adult strep presentation with rapid test positive.',
      },
      state: {
        workflowMode: 'guided',
        region: 'CA',
        emrType: 'pssuite',
        language: 'en',
        policyModel: 'local',
        age: 12,
        weight: 40,
        sex: 'male',
        egfr: 95,
        hepaticRisk: 'normal',
        pregnancy: 'na',
        domain: 'infection',
        subtype: 'throat',
        condition: 'pharyngitis',
        symptoms: ['soreThroat', 'tonsilExudate', 'rapidStrepPos'],
        allergies: [],
        currentMeds: [],
        templateId: 'tpl-pharyngitis-ca',
      },
    },
    {
      id: 'guided-sinusitis-allergy',
      title: { en: 'Sinusitis with penicillin allergy' },
      copy: {
        en: 'Adult sinusitis needing alternative to amoxicillin.',
      },
      state: {
        workflowMode: 'guided',
        region: 'US',
        emrType: 'epic',
        language: 'en',
        policyModel: 'national',
        age: 42,
        weight: 78,
        sex: 'female',
        egfr: 88,
        hepaticRisk: 'normal',
        pregnancy: 'no',
        domain: 'infection',
        subtype: 'respiratory',
        condition: 'sinusitis',
        symptoms: ['facialPain', 'nasalDischarge', 'prolongedSymptoms'],
        allergies: ['penicillin'],
        currentMeds: [],
        templateId: 'tpl-sinusitis-us',
      },
    },
    {
      id: 'guided-depression',
      title: { en: 'Guided depression review' },
      copy: { en: 'New depression diagnosis in a 38-year-old, SSRI first-line.' },
      state: {
        workflowMode: 'guided',
        region: 'CA',
        emrType: 'pssuite',
        language: 'en',
        policyModel: 'local',
        age: 38,
        weight: 72,
        sex: 'female',
        egfr: 92,
        hepaticRisk: 'normal',
        pregnancy: 'no',
        domain: 'mental-health',
        subtype: 'mood',
        condition: 'depression',
        symptoms: ['lowMood', 'anhedonia', 'sleepChange', 'fatigue'],
        allergies: [],
        currentMeds: [],
        templateId: 'tpl-depression-sertraline-ca',
      },
    },
    {
      id: 'template-hypertension',
      title: { en: 'Template hypertension starter' },
      copy: { en: 'Fast-apply ramipril template for new hypertension with diabetes.' },
      state: {
        workflowMode: 'template',
        region: 'CA',
        emrType: 'pssuite',
        language: 'en',
        policyModel: 'local',
        age: 55,
        weight: 88,
        sex: 'male',
        egfr: 75,
        hepaticRisk: 'normal',
        pregnancy: 'na',
        domain: 'cardiovascular',
        subtype: 'bp',
        condition: 'hypertension',
        symptoms: ['stageOne', 'diabetes'],
        allergies: [],
        currentMeds: ['metformin', 'statin'],
        templateId: 'tpl-hypertension-ramipril-ca',
      },
    },
    {
      id: 'guided-gerd',
      title: { en: 'Guided GERD review' },
      copy: { en: 'GERD with chronic cough, PPI trial for a 50-year-old on NSAIDs.' },
      state: {
        workflowMode: 'guided',
        region: 'CA',
        emrType: 'pssuite',
        language: 'en',
        policyModel: 'local',
        age: 50,
        weight: 82,
        sex: 'male',
        egfr: 85,
        hepaticRisk: 'normal',
        pregnancy: 'na',
        domain: 'gi',
        subtype: 'acid-reflux',
        condition: 'gerd',
        symptoms: ['heartburn', 'regurgitation', 'chronicCough'],
        allergies: [],
        currentMeds: ['nsaid'],
        templateId: 'tpl-gerd-ppi-ca',
      },
    },
    {
      id: 'guided-oa-elderly',
      title: { en: 'OA in elderly with GI risk' },
      copy: { en: 'Knee OA in a 72-year-old on anticoagulant — topical vs oral NSAID decision.' },
      state: {
        workflowMode: 'guided',
        region: 'CA',
        emrType: 'oscar',
        language: 'en',
        policyModel: 'local',
        age: 72,
        weight: 76,
        sex: 'female',
        egfr: 62,
        hepaticRisk: 'normal',
        pregnancy: 'na',
        domain: 'msk',
        subtype: 'joint',
        condition: 'osteoarthritis',
        symptoms: ['kneeOa', 'morningStiffness', 'crepitus', 'giRisk'],
        allergies: [],
        currentMeds: ['anticoagulant', 'ppi'],
        templateId: 'tpl-oa-naproxen-ca',
      },
    },
  ],
};
