window.TOLConfig = {
  UI_TEXT: {
    en: {
      eyebrow: 'Fast prescribing mock',
      heroCopy:
        'Fast mock for repeat prescribing.',
      reviewPill: 'Guided + fast-apply',
      startTour: 'Walkthrough',
      loadScenario: 'Load demo case',
      processContext: 'Process prescribing review',
      processingContext: 'Processing review...',
      controlKicker: 'Patient, market, and workflow context',
      controlTitle: 'Build a reviewable prescribing draft',
      mockEngine: 'Deterministic mock engine',
      patientContextKicker: 'Patient essentials',
      patientContextTitle: 'Start with the minimum patient context',
      marketContextKicker: 'Market and output',
      marketContextTitle: 'Choose where the order will land',
      region: 'Country / region',
      emrType: 'EMR output',
      language: 'Language',
      policyModel: 'Policy model',
      age: 'Age',
      weight: 'Weight (kg)',
      sex: 'Sex',
      egfr: 'eGFR',
      hepaticRisk: 'Hepatic review',
      pregnancy: 'Pregnancy context',
      workflowTitle: 'Choose how the doctor wants to work',
      workflowHint:
        'Either narrow a case step by step or jump straight into a saved template.',
      guidedMode: 'Guided prescribing',
      guidedModeCopy: 'Start from a general complaint and narrow down.',
      templateMode: 'Saved template / fast apply',
      templateModeCopy: 'Jump into a clinician-authored template with guardrails.',
      guidedTitle: 'Narrow the case from general to specific',
      guidedHint:
        'Move from a broad complaint to a condition, then optionally add symptoms or clues.',
      domain: 'Clinical area',
      subtype: 'Subtype',
      condition: 'Specific condition',
      symptoms: 'Optional symptoms / clues',
      symptomsHint: 'Select multiple or skip. These change ranking and reminders.',
      templateTitle: 'Use or edit a reusable template',
      templateHint:
        'Templates act like clinician-authored fast-apply packs, but the patient still has to fit the saved guardrails.',
      templateLibrary: 'Template library',
      templateLibraryHint: 'Pick the doctor-owned template that best matches the case.',
      templateEditor: 'Template guardrails',
      templateEditorHint:
        'This is where a doctor would define age and weight bands, the target condition, the default medication, and notes.',
      templateName: 'Template name',
      templateCondition: 'Template condition',
      templateDefaultMedication: 'Default medication',
      templateAgeMin: 'Min age',
      templateAgeMax: 'Max age',
      templateWeightMin: 'Min weight',
      templateWeightMax: 'Max weight',
      templateEmrType: 'Default EMR output',
      templateNotes: 'Template notes',
      newTemplate: 'New template draft',
      saveTemplate: 'Save template draft',
      allergies: 'Allergies / exclusions',
      allergyHint: 'Toggle patient factors that should change what can be used.',
      currentMeds: 'Current medicines',
      medHint: 'Use these to trigger interaction and duplication reminders.',
      scenarios: 'Demo starters',
      scenarioHint: 'One-click starting points for showing both flows.',
      summaryLabel: 'Current review',
      workflowSummary: 'Workflow',
      templateSummary: 'Template',
      eligibleCount: 'Usable',
      cautionCount: 'Needs review',
      blockedCount: 'Blocked',
      optionsKicker: 'Medication canvas',
      optionsTitle: 'Alternative medication packages',
      eligible: 'Usable',
      caution: 'Needs review',
      blocked: 'Blocked',
      patientSignals: 'Patient signals',
      checklistTitle: 'Checks and reminders',
      checklistHint: 'The product explains what it noticed before a clinician decides.',
      noChecksTitle: 'No extra review flags',
      noChecks:
        'The current mock input did not trigger extra renal, pregnancy, symptom-escalation, or interaction reminders beyond the visible option logic.',
      levelInfo: 'Info',
      levelCaution: 'Caution',
      levelBlocked: 'Blocked',
      templateFit: 'Template fit',
      templateFitHint:
        'Saved templates never bypass patient checks; they only speed up repeat workflows.',
      templateFitPass: 'Template guardrails passed',
      templateFitWarn: 'Template fit needs manual review',
      templateFitBlock: 'Template is outside saved guardrails',
      templateFitNone: 'No saved template is active in this review.',
      selectedOption: 'Primary order package',
      selectedHint:
        'This section shows the first draft, why clinicians choose it, tradeoffs, and copy-ready output.',
      doseWorkflow: 'Dose and use',
      explanation: 'Why clinicians choose it',
      pros: 'Pros',
      cons: 'Cons',
      copyPack: 'Copy-ready output',
      copyRx: 'Rx text',
      copyChart: 'Chart note',
      copyPharmacy: 'Pharmacy note',
      copied: 'Copied',
      marketMap: 'Market map',
      marketHint: 'Same clinical idea, different local overlays and terminology.',
      auditTrail: 'Audit trail',
      auditHint: 'The review stays traceable: workflow, template, patient fit, and final package.',
      noOption: 'Choose an option card to inspect its reasoning and copy pack.',
      emptyMarket: 'No options are mapped for this review yet.',
      price: 'Indicative price',
      marketCode: 'Terminology',
      preferredTag: 'Locally preferred',
      reviewOnlyTag: 'Review branch',
      marketStatus: 'Market status',
      patientSummary: 'Patient-fit signals',
      outputKicker: 'Processed prescribing review',
      outputTitle: 'Reviewable prescribing output',
      outputCopy:
        'The section below appears only after the current snapshot is processed, so the doctor can confirm context first.',
      pendingTitle: 'Context first, draft second',
      pendingBody:
        'Choose patient essentials, market output, and either a guided path or a saved template. Results stay hidden until you process the snapshot.',
      readyTitle: 'Processed draft ready',
      readyBody:
        'The output below matches only the last confirmed snapshot. Any edit requires processing again.',
      processingTitle: 'Building the review',
      processingBody:
        'Checking template fit, ranking medication packages, and preparing copy-ready output.',
      workflowGuidedLabel: 'Guided path',
      workflowTemplateLabel: 'Saved template',
      auditCaptured: 'Confirmed snapshot captured',
      auditWorkflow: 'Workflow branch resolved',
      auditTemplate: 'Saved template applied',
      auditRules: 'Medication packages ranked',
      auditSelected: 'Primary order package prepared',
      auditSessionTitle: 'Processed snapshot',
      outputTemplateNone: 'Guided review only',
      copyNoteDemo: 'Mock content only. Do not use clinically.',
      copyIndication: 'Indication',
      copyTemplate: 'Template',
      tourTryLabel: 'Try this',
      tourBack: 'Back',
      tourNext: 'Next',
      tourDone: 'Finish tour',
    },
    fr: {},
  },
  REGIONS: [
    { value: 'CA', en: 'Canada', fr: 'Canada', locale: 'en-CA', currency: 'CAD', system: 'DIN' },
    { value: 'US', en: 'United States', fr: 'Etats-Unis', locale: 'en-US', currency: 'USD', system: 'RxNorm' },
    { value: 'UK', en: 'United Kingdom', fr: 'Royaume-Uni', locale: 'en-GB', currency: 'GBP', system: 'dm+d' },
  ],
  SUBREGIONS: {
    CA: [
      { value: 'ON', en: 'Ontario', fr: 'Ontario' },
      { value: 'BC', en: 'British Columbia', fr: 'Colombie-Britannique' },
      { value: 'AB', en: 'Alberta', fr: 'Alberta' },
      { value: 'QC', en: 'Quebec', fr: 'Quebec' },
      { value: 'MB', en: 'Manitoba', fr: 'Manitoba' },
      { value: 'SK', en: 'Saskatchewan', fr: 'Saskatchewan' },
      { value: 'NS', en: 'Nova Scotia', fr: 'Nouvelle-Ecosse' },
      { value: 'NB', en: 'New Brunswick', fr: 'Nouveau-Brunswick' },
      { value: 'NL', en: 'Newfoundland and Labrador', fr: 'Terre-Neuve-et-Labrador' },
      { value: 'PE', en: 'Prince Edward Island', fr: 'Ile-du-Prince-Edouard' },
      { value: 'NT', en: 'Northwest Territories', fr: 'Territoires du Nord-Ouest' },
      { value: 'YT', en: 'Yukon', fr: 'Yukon' },
      { value: 'NU', en: 'Nunavut', fr: 'Nunavut' },
    ],
    US: [
      { value: 'ALL', en: 'All states', fr: 'Tous les etats' },
    ],
    UK: [
      { value: 'ENG', en: 'England', fr: 'Angleterre' },
      { value: 'SCT', en: 'Scotland', fr: 'Ecosse' },
      { value: 'WLS', en: 'Wales', fr: 'Pays de Galles' },
      { value: 'NIR', en: 'Northern Ireland', fr: 'Irlande du Nord' },
    ],
  },
  EMR_TYPES: [
    { value: 'pssuite', en: 'PS Suite style', fr: 'Style PS Suite' },
    { value: 'oscar', en: 'OSCAR Pro style', fr: 'Style OSCAR Pro' },
    { value: 'epic', en: 'Epic-style paste', fr: 'Style Epic' },
    { value: 'athena', en: 'Athena / generic US', fr: 'Style Athena / US generic' },
  ],
  POLICY_MODELS: [
    { value: 'local', en: 'Local formulary', fr: 'Formulaire local' },
    { value: 'national', en: 'National default', fr: 'Defaut national' },
    { value: 'value', en: 'Cost-aware review', fr: 'Revue orientee cout' },
  ],
  WORKFLOW_MODES: [
    { value: 'guided', en: 'Guided prescribing', fr: 'Prescription guidee' },
    { value: 'template', en: 'Saved template / fast apply', fr: 'Modele enregistre / application rapide' },
    { value: 'lookup', en: 'Lookup / formulary browser', fr: 'Consultation / navigateur formulaire' },
  ],
  HEPATIC_OPTIONS: [
    { value: 'normal', en: 'No major hepatic concern', fr: 'Pas de grande alerte hepatique' },
    { value: 'mild', en: 'Mild review needed', fr: 'Revue legere necessaire' },
    { value: 'major', en: 'Major review needed', fr: 'Revue importante necessaire' },
  ],
  PREGNANCY_OPTIONS: [
    { value: 'na', en: 'Not applicable / unknown', fr: 'Non applicable / inconnu' },
    { value: 'no', en: 'No', fr: 'Non' },
    { value: 'yes', en: 'Yes', fr: 'Oui' },
  ],
  DOMAINS: [
    { value: 'infection', en: 'Infection', fr: 'Infection' },
    { value: 'sti', en: 'STI', fr: 'IST' },
    { value: 'mental-health', en: 'Mental health', fr: 'Sante mentale' },
    { value: 'cardiovascular', en: 'Cardiovascular', fr: 'Cardiovasculaire' },
    { value: 'endocrine', en: 'Endocrine / metabolic', fr: 'Endocrinien / metabolique' },
    { value: 'gi', en: 'Gastrointestinal', fr: 'Gastro-intestinal' },
    { value: 'msk', en: 'Musculoskeletal / pain', fr: 'Musculosquelettique / douleur' },
    { value: 'dermatology', en: 'Dermatology', fr: 'Dermatologie' },
    { value: 'womens-health', en: "Women's health", fr: 'Sante des femmes' },
    { value: 'ent', en: 'ENT / allergy', fr: 'ORL / allergie' },
    { value: 'resp-chronic', en: 'Chronic respiratory', fr: 'Respiratoire chronique' },
  ],
  SUBTYPES: [
    { value: 'urinary', domain: 'infection', en: 'Urinary infection', fr: 'Infection urinaire' },
    { value: 'skin', domain: 'infection', en: 'Skin infection', fr: 'Infection cutanee' },
    { value: 'ear', domain: 'infection', en: 'Ear infection', fr: 'Infection de l oreille' },
    { value: 'throat', domain: 'infection', en: 'Throat infection', fr: 'Infection de la gorge' },
    { value: 'respiratory', domain: 'infection', en: 'Respiratory infection', fr: 'Infection respiratoire' },
    { value: 'eye', domain: 'infection', en: 'Eye infection', fr: 'Infection oculaire' },
    { value: 'dental', domain: 'infection', en: 'Dental infection', fr: 'Infection dentaire' },
    { value: 'systemic', domain: 'infection', en: 'Systemic / tick-borne', fr: 'Systemique / transmise par tique' },
    { value: 'common-sti', domain: 'sti', en: 'Common STI review', fr: 'Revue IST courante' },
    { value: 'vaginal', domain: 'sti', en: 'Vaginal infection', fr: 'Infection vaginale' },
    { value: 'mood', domain: 'mental-health', en: 'Mood disorder', fr: 'Trouble de l humeur' },
    { value: 'anxiety-disorder', domain: 'mental-health', en: 'Anxiety disorder', fr: 'Trouble anxieux' },
    { value: 'sleep', domain: 'mental-health', en: 'Sleep disorder', fr: 'Trouble du sommeil' },
    { value: 'bp', domain: 'cardiovascular', en: 'Blood pressure', fr: 'Pression arterielle' },
    { value: 'lipid', domain: 'cardiovascular', en: 'Lipid management', fr: 'Gestion des lipides' },
    { value: 'diabetes', domain: 'endocrine', en: 'Diabetes', fr: 'Diabete' },
    { value: 'thyroid', domain: 'endocrine', en: 'Thyroid disorder', fr: 'Trouble thyroidien' },
    { value: 'nutritional', domain: 'endocrine', en: 'Nutritional deficiency', fr: 'Carence nutritionnelle' },
    { value: 'acid-reflux', domain: 'gi', en: 'Acid-related disorder', fr: 'Trouble lie a l acidite' },
    { value: 'peptic', domain: 'gi', en: 'Peptic / H. pylori', fr: 'Ulcere peptique / H. pylori' },
    { value: 'back-pain', domain: 'msk', en: 'Back pain', fr: 'Douleur dorsale' },
    { value: 'joint', domain: 'msk', en: 'Joint disorder', fr: 'Trouble articulaire' },
    { value: 'crystal', domain: 'msk', en: 'Crystal arthropathy', fr: 'Arthropathie cristalline' },
    { value: 'headache', domain: 'msk', en: 'Headache', fr: 'Cephalee' },
    { value: 'acne-derm', domain: 'dermatology', en: 'Acne', fr: 'Acne' },
    { value: 'eczema-derm', domain: 'dermatology', en: 'Eczema / dermatitis', fr: 'Eczema / dermatite' },
    { value: 'contraception', domain: 'womens-health', en: 'Contraception', fr: 'Contraception' },
    { value: 'perimenopause', domain: 'womens-health', en: 'Perimenopause / menopause', fr: 'Perimenopause / menopause' },
    { value: 'nasal', domain: 'ent', en: 'Nasal / sinus allergy', fr: 'Allergie nasale / sinusale' },
    { value: 'obstructive', domain: 'resp-chronic', en: 'Obstructive lung disease', fr: 'Maladie pulmonaire obstructive' },
  ],
  ALLERGY_OPTIONS: [
    { value: 'penicillin', en: 'Penicillin / beta-lactam', fr: 'Penicilline / beta-lactame' },
    { value: 'sulfonamide', en: 'Sulfonamide', fr: 'Sulfonamide' },
    { value: 'macrolide', en: 'Macrolide', fr: 'Macrolide' },
    { value: 'tetracycline', en: 'Tetracycline', fr: 'Tetracycline' },
    { value: 'nsaid', en: 'NSAID / ASA', fr: 'AINS / AAS' },
    { value: 'fluoroquinolone', en: 'Fluoroquinolone', fr: 'Fluoroquinolone' },
    { value: 'ace-inhibitor', en: 'ACE inhibitor (cough / angioedema)', fr: 'IECA (toux / angioedeme)' },
    { value: 'statin-allergy', en: 'Statin intolerance', fr: 'Intolerance aux statines' },
  ],
  CURRENT_MED_OPTIONS: [
    { value: 'statin', en: 'Statin', fr: 'Statine' },
    { value: 'warfarin', en: 'Warfarin', fr: 'Warfarine' },
    { value: 'anticoagulant', en: 'Other anticoagulant', fr: 'Autre anticoagulant' },
    { value: 'ssri', en: 'SSRI', fr: 'ISRS' },
    { value: 'qtRisk', en: 'QT-prolonging medicine', fr: 'Medicament a risque QT' },
    { value: 'nsaid', en: 'NSAID', fr: 'AINS' },
    { value: 'ace-inhibitor', en: 'ACE inhibitor', fr: 'IECA' },
    { value: 'diuretic', en: 'Diuretic', fr: 'Diuretique' },
    { value: 'metformin', en: 'Metformin', fr: 'Metformine' },
    { value: 'insulin', en: 'Insulin', fr: 'Insuline' },
    { value: 'lithium', en: 'Lithium', fr: 'Lithium' },
    { value: 'opioid', en: 'Opioid', fr: 'Opioide' },
    { value: 'betaBlocker', en: 'Beta-blocker', fr: 'Beta-bloquant' },
    { value: 'maoi', en: 'MAOI', fr: 'IMAO' },
    { value: 'ppi', en: 'PPI', fr: 'IPP' },
  ],
  state: {
    workflowMode: 'guided',
    region: 'CA',
    subRegion: 'ON',
    emrType: 'pssuite',
    language: 'en',
    policyModel: 'local',
    age: 0,
    weight: 0,
    sex: 'female',
    egfr: 90,
    hepaticRisk: 'normal',
    pregnancy: 'no',
    domain: '',
    subtype: '',
    condition: '',
    symptoms: [],
    allergies: [],
    currentMeds: [],
    templateId: '',
    patientPresetId: '',
  },
};
